// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function DeleteRule(name: string): $CancellablePromise<void> {
    return $Call.ByID(3880024235, name);
}

export function Download(url: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3367144066, url, name);
}

export function GetAllowLAN(): $CancellablePromise<boolean> {
    return $Call.ByID(683052846);
}

export function GetPort(): $CancellablePromise<number | null> {
    return $Call.ByID(1688648537);
}

export function GetProfiles(): $CancellablePromise<string[]> {
    return $Call.ByID(2493533808).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProxies(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(1268542794).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        $result[1] = $$createType0($result[1]);
        return $result;
    });
}

export function GetRules(): $CancellablePromise<string[]> {
    return $Call.ByID(192794241).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSelectedProfile(): $CancellablePromise<number | null> {
    return $Call.ByID(2568240376);
}

export function GetSelectedProxy(): $CancellablePromise<number | null> {
    return $Call.ByID(2623271121);
}

export function GetSelectedRule(): $CancellablePromise<string | null> {
    return $Call.ByID(2160096249);
}

export function ReadProfiles(): $CancellablePromise<number | null> {
    return $Call.ByID(863810156);
}

export function ReadProxies(): $CancellablePromise<number | null> {
    return $Call.ByID(1915616478);
}

export function ReadRule(name: string): $CancellablePromise<string> {
    return $Call.ByID(2571073612, name);
}

export function ReadRules(): $CancellablePromise<void> {
    return $Call.ByID(2112506669);
}

export function ScanFolder(): $CancellablePromise<string | null> {
    return $Call.ByID(1994113603);
}

export function UpdateSelectedProfile(index: number | null): $CancellablePromise<void> {
    return $Call.ByID(3010063943, index);
}

export function UpdateSelectedProxy(index: number | null): $CancellablePromise<void> {
    return $Call.ByID(189746918, index);
}

export function WriteProfiles(): $CancellablePromise<void> {
    return $Call.ByID(405335087);
}

export function WriteRule(name: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2860601211, name, content);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
