// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Download(url: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3367144066, url, name);
}

export function GetProfiles(): $CancellablePromise<string[]> {
    return $Call.ByID(2493533808).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProxies(file: string): $CancellablePromise<number> {
    return $Call.ByID(1268542794, file);
}

export function GetStream(): $CancellablePromise<void> {
    return $Call.ByID(2499540926);
}

export function ParseProxies(): $CancellablePromise<string[]> {
    return $Call.ByID(2672512555).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3114879498);
}

export function UpdateProxy(index: number): $CancellablePromise<void> {
    return $Call.ByID(260160165, index);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
