// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetProfiles(): $CancellablePromise<string[]> {
    return $Call.ByID(2493533808).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProxies(file: string): $CancellablePromise<number> {
    return $Call.ByID(1268542794, file);
}

export function ParseProxies(): $CancellablePromise<string[]> {
    return $Call.ByID(2672512555).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
